# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec1e46fe9e56a034066955e0c81eb4d55e4ebeba760e84ec1aa2758e84fcd9842af3b46bc3fab65a246ea742ebd1bcb30fd2826d11716379d6941c543c6285a6

test:
  secret_key_base: a31c6b5ab342e58a040cb987b5607ff083a5ba6dbb23c4b1b0e6c636b66cc67fc9fb534c367677efc2bc68a96f9c17ba84e87ee54862a749aa66855358823984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
